#!/bin/bash

if [ ! -d .venv ]; then
	python3 -m venv .venv
	source .venv/bin/activate
	pip install wheel
	pip install --upgrade -r requirements.txt
	pip install --upgrade -r requirements-dev.txt
else
	source .venv/bin/activate
fi
